apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
    app: {{ .Values.frontend.name }}
    component: frontend
data:
  nginx.conf: |
    server {
        listen {{ .Values.frontend.service.port }};
        server_name _;
        location / {
            root /usr/share/nginx/html/;
            index index.html;
            try_files $uri $uri/ =404;
        }
        location /api/ {
            proxy_pass http://{{ .Values.backend.name }}-service:{{ .Values.backend.service.port }}/;
        }
    }