apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.frontend.name }}
    component: frontend
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}